#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle
#
#   Resulting JVM options can be specified through an environment variable
#   or via the command line.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    expr "$link" : '/.*' > /dev/null || link=`dirname "$PRG"`/"$link"
    PRG="$link"
done
app_home=`dirname "$PRG"`
# make it absolute
app_home=`cd "$app_home" && pwd`

app_name="Gradle"
greG_CMD=""

# Use the maximum available, or set MAX count.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the java executable
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$non_null_test" = "false" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$lock" = "false" ] ; then
            ulimit -n $MAX_FD_LIMIT
        fi
    fi
fi

# For Cygwin, switch paths to Windows format before running java
if $cygwin ; then
    app_home=`cygpath --path --mixed "$app_home"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
    JAVACMD=`cygpath --unix "$JAVACMD"`

    # We build the pattern for arguments to be converted via cygpath
    ROOT_RAW=`cygpath -w /`
    root_cygwin=`echo "$ROOT_RAW" | sed 's,\\,/,g'`
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_EXE" ] ; then
    WORLD_JAVA="$JAVA_EXE"
else
    WORLD_JAVA="$JAVACMD"
fi

# Split up the JVM_OPTS And GRADLE_OPTS values accordingly
if [ "" = "true" ] ; then
    exec "$WORLD_JAVA" $JAVA_OPTS -jar "$app_home/lib/gradle-wrapper.jar" "$@"
else
    exec "$WORLD_JAVA" $JAVA_OPTS \
         -classpath "$app_home/lib/gradle-wrapper.jar" \
         org.gradle.wrapper.GradleWrapperMain "$@"
fi
